#ifndef ENEMY_ASSETS_HPP
#define ENEMY_ASSETS_HPP


//put things here like range, possible positions, etc for enemies
//not image rects - keep that to assets

#define FOREST_SCOURGE_DFS_POS_1 {100, 150}
#define FOREST_SCOURGE_DFS_POS_2 {380, 30}
#define FOREST_SCOURGE_DFS_POS_3 {520, 345}
#define FOREST_SCOURGE_DFS_POS_4 {280, 412}
#define FOREST_SCOURGE_DFS_POS_5 {425, 685}
#define FOREST_SCOURGE_DFS_POS_6 {105, 875}

#define FOREST_SCOURGE_DFN_POS_1 {600, 100}
#define FOREST_SCOURGE_DFN_POS_2 {45, 100}
#define FOREST_SCOURGE_DFN_POS_3 {115, 305}
#define FOREST_SCOURGE_DFN_POS_4 {855, 305}
#define FOREST_SCOURGE_DFN_POS_5 {760, 510}
#define FOREST_SCOURGE_DFN_POS_6 {90, 510}

#define FOREST_SCOURGE_HITBOX_OFFSET_X 28
#define FOREST_SCOURGE_HITBOX_OFFSET_Y 31
#define FOREST_SCOURGE_HITBOX_WIDTH 11
#define FOREST_SCOURGE_HITBOX_HEIGHT 16
#define FOREST_SCOURGE_HEALTH 1.4f
#define FOREST_SCOURGE_SPEED 1
#define FOREST_SCOURGE_CHASE_SPEED 60.0f
#define FOREST_SCOURGE_DAMAGE 0.2
#define FOREST_SCOURGE_CHASE_DETECT_OFFSET_X 32
#define FOREST_SCOURGE_CHASE_DETECT_OFFSET_Y 32
#define FOREST_SCOURGE_CHASE_DETECT_WIDTH 128
#define FOREST_SCOURGE_CHASE_DETECT_HEIGHT 128
#define FOREST_SCOURGE_ATTACK_DETECT_OFFSET_X 32
#define FOREST_SCOURGE_ATTACK_DETECT_OFFSET_Y 32
#define FOREST_SCOURGE_ATTACK_DETECT_WIDTH 32
#define FOREST_SCOURGE_ATTACK_DETECT_HEIGHT 32
#define FOREST_SCOURGE_ATTACK_WIDTH 32
#define FOREST_SCOURGE_ATTACK_HEIGHT 16

#define THE_REGROWN_COLLISION_RECT_1 {107, 47, 35, 20}
#define THE_REGROWN_COLLISION_RECT_2 {176, 47, 37, 20}
#define THE_REGROWN_COLLISION_RECT_3 {142, 66, 34, 11}
#define THE_REGROWN_HEALTH 1
#define THE_REGROWN_RECT_OFFSET_X 48
#define THE_REGROWN_RECT_OFFSET_Y 51
#define THE_REGROWN_RECT_WIDTH 32
#define THE_REGROWN_RECT_HEIGHT 30
#define THE_REGROWN_POS {96, -8}
#define THE_REGROWN_RIGHT_ATTACK_DETECT_OFFSET_X 73
#define THE_REGROWN_RIGHT_ATTACK_DETECT_OFFSET_Y 15
#define THE_REGROWN_LEFT_ATTACK_DETECT_OFFSET_X 13
#define THE_REGROWN_LEFT_ATTACK_DETECT_OFFSET_Y 15
#define THE_REGROWN_ARM_ATTACK_DETECT_WIDTH 42
#define THE_REGROWN_ARM_ATTACK_DETECT_HEIGHT 100
#define THE_REGROWN_ARM_DAMAGE 0.5
#define THE_REGROWN_GROUND_ATTACK_COOLDOWN 1.5f

#endif