#include "img_rects.hpp"

Rectangle health_bar_left_end = {1, 1, 2, 6};
Rectangle health_bar_right_end = {14, 1, 2, 6};
Rectangle health_bar_right_middle = {4, 1, 1, 6};
Rectangle health_bar_middle = {6, 1, 1, 6};
Rectangle health_bar_left_middle = {8, 1, 1, 6};
Rectangle health_bar_middle_dead = {10, 1, 1, 6};
Rectangle health_bar_middle_left_dead = {12, 1, 1, 6};

Rectangle stamina_bar_dead = {1, 8, 1, 5};
Rectangle stamina_bar_segment = {3, 8, 1, 5};

Rectangle start_menu_text_rect = {0, 0, 288, 96};
Rectangle start_menu_emination = {0, 96, 320, 112};
Rectangle start_menu_options_rect = {288, 16, 112, 64};
Rectangle start_menu_select_left = {288, 0, 16, 16};
Rectangle start_menu_select_right = {304, 0, 16, 16};
Rectangle start_menu_saves_select_screen = {400, 0, 320, 192};
Rectangle start_menu_saves_select_screen_selecter = {720, 0, 82, 146};
Rectangle start_menu_credits_screen = {0, 208, 320, 180};
Rectangle start_menu_achievements_screen = {320, 208, 320, 180};
Rectangle start_menu_options_screen = {640, 208, 320, 180};


Rectangle inv_cursor_anim[2] = {
    {0, 0, 32, 18},
    {0, 32, 32, 18}};

// windmill stuff

Rectangle village_windmill_animation[4] = {
    {96, 0, VILLAGE_WINDMILL_WIDTH, VILLAGE_WINDMILL_HEIGHT},
    {240, 0, VILLAGE_WINDMILL_WIDTH, VILLAGE_WINDMILL_HEIGHT},
    {384, 0, VILLAGE_WINDMILL_WIDTH, VILLAGE_WINDMILL_HEIGHT},
    {528, 0, VILLAGE_WINDMILL_WIDTH, VILLAGE_WINDMILL_HEIGHT}};

// map stuff


// non-constant asset stuff
Rectangle start_bulldozer_animation[3] = {
    {128, 0, START_BULLDOZER_WIDTH, START_BULLDOZER_HEIGHT},
    {240, 0, START_BULLDOZER_WIDTH, START_BULLDOZER_HEIGHT},
    {352, 0, START_BULLDOZER_WIDTH, START_BULLDOZER_HEIGHT}};


Rectangle start_portal_animation[4] = {
    {0, 0, START_PORTAL_WIDTH, START_PORTAL_HEIGHT},
    {48, 0, START_PORTAL_WIDTH, START_PORTAL_HEIGHT},
    {96, 0, START_PORTAL_WIDTH, START_PORTAL_HEIGHT},
    {144, 0, START_PORTAL_WIDTH, START_PORTAL_HEIGHT}};
// Rectangle start_portal_emination;

Rectangle Big_tree_levels_tree_trunk_middle = {0, 0, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128};
Rectangle Big_tree_levels_tree_trunk_bottom = {128, 0, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128};
Rectangle Big_tree_levels_tree_trunk_top = {256, 0, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128};

// player-focused stuff

//(i know i can use pointers but they scary)
Rectangle player_idle_up_arr[1] = {
    {64, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}};
Rectangle player_idle_down_arr[1] = {
    {0, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}};
Rectangle player_idle_right_arr[1] = {
    {128, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}};
Rectangle player_idle_left_arr[1] = {
    {192, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}};
// player-focused rects, in player_tex
Rectangle player_walk_down[12] = {
    {0, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {512, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {576, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {640, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {704, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}};
Rectangle player_walk_up[12] = {
    {0, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {512, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {576, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {640, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {704, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}};
Rectangle player_walk_right[8] = {
    {0, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 192, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_walk_left[8] = {
    {0, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 256, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};

Rectangle player_sword_slash_down_arr[5] = {
    {0, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_sword_slash_up_arr[5] = {
    {0, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_sword_slash_right_arr[5] = {
    {0, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_sword_slash_left_arr[5] = {
    {0, 512, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 512, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 512, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 512, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 512, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};

Rectangle player_sprint_right[8] = {
    {0, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 576, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_sprint_left[8] = {
    {0, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 640, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_sprint_up[6] = {
    {0, 704, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 704, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 704, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 704, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 704, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 704, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_sprint_down[6] = {
    {0, 768, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 768, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 768, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 768, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 768, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 768, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_dash_right[8] = {
    {0, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 832, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_dash_left[8] = {
    {0, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {448, 896, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_dash_up[6] = {
    {0, 960, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 960, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 960, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 960, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 960, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 960, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};
Rectangle player_dash_down[6] = {
    {0, 1024, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 1024, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 1024, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 1024, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 1024, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 1024, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
};




//forest scourge stuff
Rectangle forest_scourge_idle_down_right[3] = {
    {0, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};
Rectangle forest_scourge_idle_up_right[3] = {
    {192, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};
Rectangle forest_scourge_idle_down_left[3] = {
    {0, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};
Rectangle forest_scourge_idle_up_left[3] = {
    {192, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};
Rectangle forest_scourge_walk_down_right[7] = {
    {0, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 128, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};


Rectangle forest_scourge_walk_up_left[7] = {
    {0, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {384, 320, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};
//forest scourge attacking arrays
Rectangle forest_scourge_attack_down_right[6] = {
    {0, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 384, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};

Rectangle forest_scourge_attack_up_left[6] = {
    {0, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {192, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {256, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {320, 448, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};



//forest scourge walk animations


Rectangle the_regrown_entrance_arr[8] = {
    {0, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {128, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {256, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {384, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {512, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {640, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {768, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {896, 128, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}
};
Rectangle the_regrown_idle_arr[4] = {
    {0, 256, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}, 
    {128, 256, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}, 
    {256, 256, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}, 
    {384, 256, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}
};
Rectangle the_regrown_attack_right_arr[5] = {
    {0, 384, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {128, 384, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {256, 384, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {384, 384, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {512, 384, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}
};
Rectangle the_regrown_attack_left_arr[5] = {
    {0, 512, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {128, 512, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {256, 512, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {384, 512, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {512, 512, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}
};
Rectangle the_regrown_ground_shake_arr[6] = {
    {0, 640, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {128, 640, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {256, 640, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {384, 640, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {512, 640, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {640, 640, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}
};
Rectangle the_regrown_die_arr[14] = {
    {0, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {128, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {256, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {384, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {512, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {640, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {768, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {896, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {1024, 768, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {0, 896, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {128, 896, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {256, 896, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {384, 896, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
    {512, 896, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128},
};



Rectangle the_regrown_default_sprite_arr[1] = {{0, 0, DEFAULT_SPRITE_WIDTH_128, DEFAULT_SPRITE_HEIGHT_128}};



Rectangle village_questgiver_idle[1] = {64, 0, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT};
Rectangle village_questgiver_point[3] = {
    {0, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {64, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT},
    {128, 64, DEFAULT_SPRITE_WIDTH, DEFAULT_SPRITE_HEIGHT}
};

